language: bash

services:
  - docker

env:
  matrix:
    - REDIS_VER=4.0.10 TAGS=4.0,4,latest
    - REDIS_VER=3.2.12 TAGS=3.2,3

script:
  - make && make test

after_success:
  - . "${TRAVIS_BUILD_DIR}/release.sh"
